관통프로젝트/projects/pjt06/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/',views.login, name = 'login'),
    path('logout/', views.logout , name = 'logout'),
    path('<username>/',views.profile, name='profile'),
    path('<int:user_pk>/follow/',views.follow,name='follow'),
]

관통프로젝트/projects/pjt06/community/urls.py
from django.urls import path
from . import views


app_name = 'community'
urlpatterns = [
    path('create/', views.create, name='create'), 
    path('', views.review_list, name='review_list'),
    path('<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:review_pk>/like/', views.like, name='like_review'),
]

관통프로젝트/projects/pjt06/pjt06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

관통프로젝트/projects/pjt06/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name = 'followers')

관통프로젝트/projects/pjt06/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_review')


class Comment(models.Model):
    content = models.CharField(max_length=100)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

관통프로젝트/projects/pjt06/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields +('email',)

관통프로젝트/projects/pjt06/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ['user','like_users',]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['user', 'review']

관통프로젝트/projects/pjt06/accounts/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login , logout as auth_logout
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import get_user_model
# Create your views here.


@require_http_methods(['GET','POST'])
def signup(request):
    
    if request.user.is_authenticated:
        return redirect('community:review_list')
        
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth_login(request,user)
            return redirect('community:review_list')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:review_list')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:review_list')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html',context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:review_list')

def profile(request,username):
    person = get_object_or_404(get_user_model(),username = username)
    context = {
        'person':person,
    }
    return render(request, 'accounts/profile.html',context)

@require_POST
def follow(request,user_pk):
    person = get_object_or_404(get_user_model(),pk=user_pk)
    user = request.user
    if person != user:
        if person.followers.filter(pk=user.pk).exists():
            person.followers.remove(request.user.pk)
        else:
            person.followers.add(request.user.pk)
    return redirect('accounts:profile',person.username)

관통프로젝트/projects/pjt06/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from .models import Review, Comment
from .forms import ReviewForm, CommentForm

# Create your views here.
@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect(request.GET.get('next') or 'community:review_detail', review.pk)
    else: 
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)


def review_list(request):
    community = Review.objects.order_by('-pk')
    context = {
        'community': community,
    }
    return render(request, 'community/review_list.html', context)


def review_detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        'review': review,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'community/review_detail.html', context)


@require_POST
def create_comments(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form =CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect('community:review_detail', review.pk)
        context = {
            'comment_form' : comment_form,
            'review' : review
        }
        return render(request, 'community/review_detail.html', context)
    return redirect('accounts:login')

@require_POST
def like(request,review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review,pk=review_pk)
        if review.like_users.filter(pk=request.user.pk).exists():
            review.like_users.remove(request.user)
        else:
            review.like_users.add(request.user)
        return redirect('community:review_detail',review_pk)
    return redirect('accounts:login')            

관통프로젝트/projects/pjt06/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1 class ="text-center my-5" >LogIn</h1>
<div class="container bg-dark w-50  text-start">
<form action="{% url 'accounts:login' %}" method = 'POST' class = 'text-white' >
    {% csrf_token %}
    <br>
 {% bootstrap_form form %}
<div class = 'text-center my-5'>
<button type="submit" class="btn btn-primary btn-md  w-100">LogIn</button>
</div>
</form>
<div class = 'text-center w-100 mb-3'>
<a href="{% url 'accounts:signup'%}" class="btn btn-secondary btn-sm w-100 mb-3 ">SignUp</a>
</div>
</div>
{% endblock content %}

관통프로젝트/projects/pjt06/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class = 'container'>
<h1 class = 'text-center my-5'> <strong> {{person.username}}의 프로필 </strong></h1>
<div class="container bg-danger">
<h1 class = 'bg-dark text-white'>팔로워 수 = {{person.followers.all|length}}  | 팔로잉 수 = {{person.followings.all|length}}</h1>
<div class='bg-secondary text-white'>
<form action=" {% url 'accounts:follow' person.pk %}"method = 'POST'>
{% csrf_token %}
{% if request.user != person %}
    {% if request.user in person.followers.all %}
        <button>unfollow</button>
    {% else %}
        <button>follow</button>
    {% endif %}
{% endif %}
</form>
<h2>{{ person.username }}이 작성한 {{person.review_set.all|length}}개의 게시글</h2>
{% for review in person.review_set.all %}
  <div>{{review.pk}}번 글 - {{ review.title }}</div>
{% endfor %}
<hr>

<h2>{{ person.username }}이 작성한 댓글 {{person.comment_set.all|length}}개의 댓글</h2> 
{% for comment in person.comment_set.all %}
  <div>{{review.pk}}번 글의 댓글 - {{ comment.content }}</div>
{% endfor %}
<hr>

<h2>{{ person.username }}이 좋아요 한  {{person.like_review.all|length}} 개의 게시글</h2>
{% for review in person.like_review.all %}
<ol>
  <p><div>{{review.pk}}번 글 - {{ review.title }}</div></p>
</ol>
{% endfor %}
<hr>
</div>

</div>
</div>

<a href="{% url 'community:review_list' %}">[BACK]</a>

{% endblock content %}

관통프로젝트/projects/pjt06/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1 class ="text-center my-5">SignUp</h1>
<form action="{% url 'accounts:signup' %}" method = 'POST'>
{% csrf_token %}
<div class = 'container bg-dark w-50 text-white'>
 {% bootstrap_form form %}
<div class = 'text-center'>
<button type= 'submit' class = 'btn btn-primary btn-md'>회원가입</button>
</div>
</div>

<br>
</div>
</form>
{% endblock content %}

관통프로젝트/projects/pjt06/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.0/css/all.css" integrity="sha384-OLYO0LymqQ+uHXELyx93kblK5YIS3B2ZfLGBmsJaUyor7CpMTBsahDHByqSuWW+q" crossorigin="anonymous">
  <title>pjt06</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-white" href="">Community</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'community:review_list'%}">Review list <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="{% url 'community:create'%}">New review <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    {% if request.user.is_authenticated %}
      <form action="{% url 'accounts:logout' %}" method='POST' class='form-inline my-2 my-lg-0'>
        {% csrf_token %}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">logout</button>
      </form>
    {% else %}
      <form class="form-inline my-2 my-lg-0 mx-1" action="{% url 'accounts:signup'%}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">SignUp</button>
      </form>
      <form class="form-inline my-2 my-lg-0" action="{% url 'accounts:login'%}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">LogIn</button>
      </form>
    {% endif %}
  </div>
</nav>
  <div class="container">
      {% block content %}
      {% endblock content %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>