관통프로젝트/projects/pjt05/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/',views.login, name = 'login'),
    path('logout/', views.logout , name = 'logout'),
]

관통프로젝트/projects/pjt05/community/urls.py
from django.urls import path
from . import views


app_name = 'community'
urlpatterns = [
    path('create/', views.create, name='create'), 
    path('', views.review_list, name='review_list'),
    path('<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:review_pk>/comments/', views.create_comments, name='create_comments')
]

관통프로젝트/projects/pjt05/pjt05/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

관통프로젝트/projects/pjt05/accounts/models.py
from django.db import models

# Create your models here.

관통프로젝트/projects/pjt05/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.CharField(max_length=100)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

관통프로젝트/projects/pjt05/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ['user',]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['user', 'review']

관통프로젝트/projects/pjt05/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login as auth_login , logout as auth_logout
from django.views.decorators.http import require_http_methods, require_POST
# Create your views here.

@require_http_methods(['GET','POST'])
def signup(request):
    
    if request.user.is_authenticated:
        return redirect('community:review_list')
        
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth_login(request,user)
            return redirect('community:review_list')
    else:
        form = UserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:review_list')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:review_list')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html',context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:review_list')

관통프로젝트/projects/pjt05/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from .models import Review, Comment
from .forms import ReviewForm, CommentForm

# Create your views here.
@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect(request.GET.get('next') or 'community:review_detail', review.pk)
    else: 
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)


def review_list(request):
    community = Review.objects.order_by('-pk')
    context = {
        'community': community,
    }
    return render(request, 'community/review_list.html', context)


def review_detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        'review': review,
        'comment_form' : comment_form,
        'comments' : comments,
    }
    return render(request, 'community/review_detail.html', context)


@require_POST
def create_comments(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form =CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect('community:review_detail', review.pk)
        context = {
            'comment_form' : comment_form,
            'review' : review
        }
        return render(request, 'community/review_detail.html', context)
    return redirect('accounts:login')

관통프로젝트/projects/pjt05/community/templates/community/form.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">CREATE</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Create</button>
  </form>
  <a href="{% url 'community:review_list' %}" class="btn btn-secondary btn-sm">Back</a>
{% endblock content %}

관통프로젝트/projects/pjt05/community/templates/community/review_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class='text-center'>DETAIL</h2>
  <h3>No. {{ review.pk }}</h3>
  <hr>
  <p>Title : {{ review.title }}</p>
  <p>movie Title : {{ review.movie_title }}</p>
  <p>Content: {{ review.content }}</p>
  <p>Rank: {{ review.rank }}</p>
  <p>Created at: {{ review.created_at|date:"SHORT_DATE_FORMAT" }}</p>
  <p>Updated at: {{ review.updated_at|date:"M j, Y" }}</p>
  <hr>
  <a href="{% url 'community:review_list'%}">back</a>
  <hr>
  {{ comments|length }}개의 댓글
  {% for comment in comments %}
    <li>{{ comment.content }}</li>
  {% endfor %}
  <form action="{% url 'community:create_comments' review.pk %}" method='POST'>
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button>submit comment</button>
  </form>
{% endblock  %}

관통프로젝트/projects/pjt05/community/templates/community/review_list.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="text-center my-5">Community</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Title</th>
        <th scope="col">Movie Title</th>
        <th scope="col">Rank</th>
      </tr>
    </thead>
    <tbody>
      {% for review in community %}
        <tr>
          <th scope="row">{{ review.pk }}</th>
          <td><a href="{% url 'community:review_detail' review.pk %}">{{ review.title }}</a></td>
          <td>{{ review.movie_title }}</td>
          <td>{{ review.rank }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

관통프로젝트/projects/pjt05/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <title>pjt04</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Community</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'community:review_list'%}">Review list <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'community:create'%}">New review <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    {% if request.user.is_authenticated %}
      <form action="{% url 'accounts:logout' %}" method='POST' class='form-inline my-2 my-lg-0'>
        {% csrf_token %}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">logout</button>
      </form>
    {% else %}
      <form class="form-inline my-2 my-lg-0 mx-1" action="{% url 'accounts:signup'%}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">SignUp</button>
      </form>
      <form class="form-inline my-2 my-lg-0" action="{% url 'accounts:login'%}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">LogIn</button>
      </form>
    {% endif %}
  </div>
</nav>
  <div class="container">
      {% block content %}
      {% endblock content %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>