javascript/연습/1015_practice/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

javascript/연습/1015_practice/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

javascript/연습/1015_practice/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/dacf7dcd9c.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% if request.user.is_authenticated %}
      <h3>Hello, {{ user.username }}</h3>
      <a href="{% url 'accounts:update' %}">정보수정</a>
      <a href="{% url 'accounts:logout' %}">Logout</a>
      <a href="{% url 'accounts:profile' request.user.username %}">내프로필</a>
      {% comment %} 버튼을 눌렀을 때 폼으로 요청이 가니까 {% endcomment %}
      {% comment %} 버튼을 누르기보다 폼을 건들여보자! {% endcomment %}
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="회원탈퇴">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">Login</a>
      <a href="{% url 'accounts:signup' %}">Signup</a>
    {% endif %}
    <hr>
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <!-- axios CDN을 가져옴! -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const forms = document.querySelectorAll('.like-form')
    //foreach -> 인자로 각요소인 form이 들어감!
    // csrftoken가져옴, input type이 hidden인 것은 나중에 같은 것이 나올수도 있지만 name이 csrftoken인 것은 이거밖에 없을 것같다!
    const csrfTokenInput = document.querySelector('input[name="csrfmiddlewaretoken"]')
    const csrftoken = csrfTokenInput.value
    forms.forEach(form => {
      form.addEventListener('submit',(event)=>{
        //forms의 각각 form에다가 기본 submit 동작이 발생하지 않게 막아야한다
        // form의 원래 기본 동작을 막아줌!
        event.preventDefault()
        // post 요청을 like에다가 보냄!
        // post괄호 안에 { url } 이거 써도 되지만 이거말고 다르게 표현!
        // html의 article-id는 js에서 지원되지 않아서 '-i'->'I'이렇게 바뀜
        // event.target.dataset.articleId
        // event.target = form이랑 같은거기때문에 아래처럼 적어도됨!
        const articleId = form.dataset.articleId
        // 그래서 요청을보낼때 articleId를 보냄!
        //submit할 때 like 에다가 요청 보내서 응답오면(.then의 괄호안에 일을 수행!)
        // {headers: {'X-CSRFToken': csrftoken}}
        axios.post(`/articles/${articleId}/like/`,
          {},
          {headers: {'X-CSRFToken': csrftoken}}
          )
          // 응답을 인자로 넘겨줌!
            .then((response)=>{
              //응답오면 좋아요 표시 수정, 사람수 수정
              const likeBtn = document.querySelector(`#like-btn-${articleId}`)
              const likeCount = document.querySelector(`#like-count-${articleId}`)
              // // 좋아요 색 지정
              // 1. if로 쓰는 법
              // if (response.data.liked) {
              //   likeBtn.style.color = 'crimson'
              // } else {
              //   likeBtn.style.color = 'black'
              // }
              // 2. 삼항연산자로 쓰는 법
              likeBtn.style.color = response.data.liked ? 'crimson' : 'black'
              // 응답이 왔을 때 좋아요 표시
              likeCount.innerText = response.data.count
          })
      })
    })
  </script>
</body>
</html>